  name: release tag test
  on:
    push:
      tags:
        - "v*"
  jobs:
    write-version:
      runs-on: ubuntu-latest
      name: Write Version to File
      steps:
        - uses: actions/checkout@master
        - name: Update version
          uses: brettdorrans/write-version-to-file@master
          with:
            filename: 'version.json'
            placeholder: 'version'

        - name: push changes to main
          run: |
            git add .
            git commit -m "update version"
            git push
