  name: release tag test
  on:
    push:
      tags:
        - "v*"
#  jobs:
#    write-version:
#      runs-on: ubuntu-latest
#      name: Write Version to File
#      steps:
#        - uses: actions/checkout@master
#        - name: Update version
#          uses: brettdorrans/write-version-to-file@master
#          with:
#            filename: '.VERSION'
#            placeholder: '${VERSION}'
#
#        - name: push changes to main
#          run: |
#            git config --global user.email "ilajili@payplug.com"
#            git config --global user.name "ilajili"
#            git remote set-url origin https://github.com/ilajili/test-github-actions.git
#            git add .
#            git commit -m "update version"
#            git push origin HEAD:main

  jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
        - name: Get the version
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: Test
          run: |
            echo  $RELEASE_VERSION
            echo version.json > ${{ env.RELEASE_VERSION }}