  name: release test
  on:
    push:
      tags:
        - "v*"
  jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@v2
        - uses: pocket-apps/action-update-version@v1
          with:
            files: 'version.json'
            version-regexp: '\d+.\d+.\d+'
            repo-token: ${{ secrets.GITHUB_TOKEN }}