  name: release test
  on:
    push:
      tags:
        - "v*"
  jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
        - name: Get the version
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        - name: Test
          run: |
              echo $RELEASE_VERSION