  name: release test
  on:
    push:
      tags:
        - "v*"
  jobs:
    test:
      runs-on: ubuntu-18.04
      steps:
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
